### ISSUE TITLE
Crashed while raining 

### ISSUE THREAD

**Issue by P14S0P** [DragonsPlusMinecraft/VisualityReforged#5]
[crash-2023-04-12_21.11.39-client.txt](https://github.com/ChannelingMC/visuality-forge/files/11217541/crash-2023-04-12_21.11.39-client.txt)

**Comment by LarveyOfficial** [comment]
+1

**Comment by Resulon12** [comment]
+1 for me too

**Comment by RaymondBlaze** [comment]
Unlike the original fabric version, Visuality Reforged is currently not a client-side-only mod due to Forge's nature.
However, I do have a plan to reimplement the mod in a client-side-only manner and hopefully I can work it out in 1 or 2 weeks with 1.19.2 and 1.19.4 :)

**Comment by RaymondBlaze** [comment]
Fixed in version 2.0, the mod is now completely client-sided

**Comment by culliiing** [comment]
I have the 2.0 version of the mod installed client-side only and still crashes when raining.
`Registry Object not present: visuality:water_circle`
